name: Rust Build

on:
  push:
    branches: [ master, main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-skyline
      run: cargo install --git https://github.com/jam1garner/cargo-skyline
    - name: Install rust-std-skyline-squashed
      run: cd .. && git clone https://github.com/jam1garner/rust-std-skyline-squashed && cd -
    - name: Attempt to build
      run: PATH=$PATH:/usr/share/rust/.rustup/toolchains/nightly-2020-04-10-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin cargo skyline build --release
    - name: Upload compiled plugin
      uses: actions/upload-artifact@v4
      with:
        name: libarc_randomizer_folder
        path: target/aarch64-skyline-switch/release/libarc_randomizer_folder.nro

